### DISCUSSION TITLE
sp_core::to_substrate_wasm_fn_return_value 编译报错

### DISCUSSION THREAD

**Discussion by jimmychu0807** [ParityAsia/substrate-newsletter#7] [Substrate/Polkadot 技术问题]
老师，请问这个问题如何解决哈？

![WechatIMG269](https://user-images.githubusercontent.com/898091/107008939-53fe5480-67cf-11eb-8105-3275dea9a26a.png)

Cargo.toml:

```toml
[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template for kitties.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'pallet-kitties'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }
sp-std = { default-features = false, version = '2.0.0' }
pallet-randomness-collective-flip = { version = '2.0.0' }
balances = { package = 'pallet-balances', version = '2.0.0', default-features = false}


[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }
balances = { package = 'pallet-balances', version = '2.0.0', default-features = false}


[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-randomness-collective-flip/std',
    "balances/std",
    "sp-io/std",
    "sp-runtime/std",
    'sp-std/std',   
]
```

\- 昌旭
